
When spell correcting, this package forces you to fix your mistakes
   three times to re-write your muscle memory into typing it corrqectly.

* Motivation

   I used to type 'necessary' wrong... ALL THE TIME.  I misspelled it so
   often that it became part of my muscle memory.  It is one of *THOSE*
   words for me.  There are others, that by muscle or brain memory,
   are "burned in" as a particular pattern.

   This is an attempt to break that pattern, by forcing you to re-type
   your misspelled words 3 times.  This should help overcome any broken
   muscle and brain memory.

* Usage

** Fixing Spelling Mistakes 
   - Step 1 :: Require this file
   - Step 2 :: Use M-$ to check the spelling of your misspelled word
   - Step 3 :: follow the directions of the prompt

   If you want, you can customize the
   `fix-muscle-memory-load-problem-words' variable, and that will
   force you to fix the typos when you make them, rather than at
   spell-check time.  Alternatively just call
   `fix-muscle-memory-load-problem-words' with nil and an alist of
   problem words in the format of (("tyop" . "typo")).

** Helping with Extended commands

  If you find yourself using `execute-extended-command' in place of a
  keybinding, using this will help train you.  The first three
  instances of the same extended command will go through normally.
  The next time however you will be told the key-combo to use and then
  prompted to enter it three times.

** Getting out
  
  Entering in the wrong answer more than 6 times or so will exit out
  of the loop.  Alternatively C-g (quit) will get you out as well.

* Changelog

   - v 0.1 :: First Version.
   - v 0.2 ::
     - Minor documentation fix.
   - v 0.3 ::
     - Fix bug when using Ispell.
   - v 0.4 ::
     - Gave it it's own repository (finally).
     - Added abbrev hook for fixing as-you-type-mistakes.
     - properly manage the response back from `ispell-command-loop'.
     - Added cute emoji.  I couldn't help myself.
     - Added fix-muscle-memory-extended-command
